export const ACTION_TYPES = {
  UPDATE_HABIT: "UPDATE_HABIT",
  ADD_HABIT: "ADD_HABIT",
  SEND_TO_ARCHIVE: "SEND_TO_ARCHIVE",
  ARCHIVE_TO_MAIN: "ARCHIVE_TO_MAIN",
  DELETE_HABIT_FROM_MAIN: "DELETE_HABIT_FROM_MAIN",
  DELETE_HABIT_FROM_ARCHIVE: "DELETE_HABIT_FROM_ARCHIVE",
};
